language: go
addons:
  postgresql: "9.3"
go:
  - 1.3
  - 1.4
  - tip
install:
  - go get github.com/codegangsta/cli
  - go get github.com/streadway/amqp
before_script:
  - psql -c 'create database integration_test;' -U postgres
env:
  - DB_NAME=integration_test
