language: go
addons:
  postgresql: "9.3"
go:
  - 1.3
  - 1.4
  - tip
install:
  - go get github.com/codegangsta/cli
  - go get github.com/lib/pq
script:
  - go install
  - ./test.sh
cache:
  directories:
  - samples
