language: go
sudo: false
addons:
  postgresql: 9.1
go:
  - 1.3
  - 1.4
  - tip
cache:
  directories:
  - samples
install:
  - go get github.com/codegangsta/cli
  - go get github.com/lib/pq
  - ./download_samples.sh
script:
  - go install && ./test.sh
