language: go
os: linux
addons:
  postgresql: "9.4"
go:
  - "1.11"
  - tip
cache:
  directories:
  - samples
install:
  - ./download_samples.sh
script:
  - go install github.com/lukasmartinelli/pgfutter && ./test.sh
  - go test -v github.com/lukasmartinelli/pgfutter
